Plugin developer learning pathway/05 good practices
jonathanbossenger/wp-content pull request #13
Opened 2024-10-08 19:25 UTC by CrochetFeve0251

Added the script for https://github.com/WordPress/Learn/issues/2044

2024-10-22 10:23 UTC, jonathanbossenger requested changes
@CrochetFeve0251 I completed a first pass on the script, and I have a few suggestions, mostly around the use of the mermaid syntax.

There will probably be a second round of changes, mostly grammar updates and tweaks to allow for a lesson video flow, but the general content and structure is good. Nice work.

2024-10-22 10:23 UTC, jonathanbossenger commented on plugin-developer-learning-pathway/02-Advanced-Hooks/04-good-practices.md
> +```mermaid
Learn.WordPress.org doesn't support Mermaid's syntax, so it might be better to include a PHP style example.

2024-10-22 10:23 UTC, jonathanbossenger commented on plugin-developer-learning-pathway/02-Advanced-Hooks/04-good-practices.md
> +Finally, if the action is after the actual event, it is advised to use a past temps inside the name.
I think you mean past tense here?

2024-10-22 13:17 UTC, CrochetFeve0251 commented on plugin-developer-learning-pathway/02-Advanced-Hooks/04-good-practices.md
> +```mermaid
@jonathanbossenger would an image be acceptable?

2024-10-24 06:52 UTC, jonathanbossenger commented on plugin-developer-learning-pathway/02-Advanced-Hooks/04-good-practices.md
> +```mermaid
An image could work, when I record the video I can include the image in the slides on screen.

2024-10-25 13:27 UTC, jonathanbossenger commented on plugin-developer-learning-pathway/02-Advanced-Hooks/04-good-practices.md
> +```mermaid
Please let me know when you think you'll be able to add the image. I want to try and record all the lessons from this module next week.

2024-10-29 08:18 UTC, jonathanbossenger commented
@CrochetFeve0251, thanks for the updates. I will review this week.

2024-10-31 10:19 UTC, jonathanbossenger commented
@CrochetFeve0251, thanks for the script. I will merge this as is, and then create a new PR with the "recording ready" reviewed version.

2024-10-31 10:19 UTC, merged